Don't bother cd'ing within a subshell
DEST_PATH, SOURCE_PATH, and BACKUP_PATH should all be absolute paths,
so it won't matter what directory we're in

Also, simplify the find/replace of old paths

diff --git a/virtualenv-mv b/virtualenv-mv
--- a/virtualenv-mv
+++ b/virtualenv-mv
@@ -28,24 +28,19 @@ do_mv(){
         fatal "failed to move ‘$SOURCE_PATH’ to ‘$DEST_PATH’"
     }
 
-    (
-        cd "$DEST_PATH" || {
-            fatal "unable to cd into ‘$DEST_PATH’"
-        }
+    cd "$DEST_PATH" || {
+        fatal "unable to cd into ‘$DEST_PATH’"
+    }
 
-        # generate list of files to search
-        readarray -t filelist < <(find bin/ -type f
-                                  find lib/ -type f -name RECORD)
+    # find and replace old virtualenv path with new
+    (find bin/ -type f -print0; find lib/ -type f -name RECORD -print0) \
+        | xargs -0r -- rgrep --files-with-matches --null "$SOURCE_PATH" \
+        | xargs -0r -- sed -i "s:$SOURCE_PATH:$PWD:g"
 
-        # find and replace old virtualenv path with new
-        rgrep --files-with-matches --null "$SOURCE_PATH" "${filelist[@]}" \
-            | xargs -0r -- sed -i "s:$SOURCE_PATH:$PWD:g"
-
-        # fix any dangling symlinks
-        while read -rd $'\0' path; do
-            ln -fs "${path/local\/}" "$path"
-        done < <(find "$DEST_PATH/local" -type l -print0 2>/dev/null)
-    )
+    # fix any dangling symlinks
+    while read -rd $'\0' path; do
+        ln -fs "${path/local\/}" "$path"
+    done < <(find "$DEST_PATH/local" -type l -print0 2>/dev/null)
 
     remove_backup
 }
